# Generated by Django 5.1.5 on 2025-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrition',
            name='clave',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
